#!/usr/bin/env python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.
# https://projecteuler.net/problem=2

bit = 1
fib1 = 1
fib2 = 2
acc = fib2
max = 4000000
while fib1 < max and fib2 < max:
	if bit:
		fib1 = fib1 + fib2
		if fib1 % 2 == 0:
			acc = acc + fib1
	else:
		fib2 = fib1 + fib2
		if fib2 % 2 == 0:
			acc = acc + fib2
	bit = 1 - bit
print(acc)
	   